-- MySQL Script generated by MySQL Workbench
-- Sun Dec 11 18:49:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controlequiposcomputo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `controlequiposcomputo` ;

-- -----------------------------------------------------
-- Schema controlequiposcomputo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlequiposcomputo` DEFAULT CHARACTER SET utf8 ;
USE `controlequiposcomputo` ;

-- -----------------------------------------------------
-- Table `controlequiposcomputo`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlequiposcomputo`.`tipo` ;

CREATE TABLE IF NOT EXISTS `controlequiposcomputo`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(32) NOT NULL,
  `estado` VARCHAR(8) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlequiposcomputo`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlequiposcomputo`.`estado` ;

CREATE TABLE IF NOT EXISTS `controlequiposcomputo`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(32) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlequiposcomputo`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlequiposcomputo`.`marca` ;

CREATE TABLE IF NOT EXISTS `controlequiposcomputo`.`marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(32) NOT NULL,
  `estado` VARCHAR(8) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlequiposcomputo`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlequiposcomputo`.`rol` ;

CREATE TABLE IF NOT EXISTS `controlequiposcomputo`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlequiposcomputo`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlequiposcomputo`.`usuario` ;

CREATE TABLE IF NOT EXISTS `controlequiposcomputo`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(32) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `estado` TINYINT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_rol1_idx` (`rol_id` ASC),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `controlequiposcomputo`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlequiposcomputo`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlequiposcomputo`.`inventario` ;

CREATE TABLE IF NOT EXISTS `controlequiposcomputo`.`inventario` (
  `serial` VARCHAR(32) NOT NULL,
  `modelo` INT NOT NULL,
  `descripcion` VARCHAR(256) NOT NULL,
  `color` VARCHAR(32) NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `precio` DOUBLE NOT NULL,
  `estado_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  `marca_id` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`serial`),
  UNIQUE INDEX `modelo_UNIQUE` (`modelo` ASC),
  INDEX `fk_inventario_estado1_idx` (`estado_id` ASC),
  INDEX `fk_inventario_tipo1_idx` (`tipo_id` ASC),
  INDEX `fk_inventario_marca1_idx` (`marca_id` ASC),
  CONSTRAINT `fk_inventario_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `controlequiposcomputo`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `controlequiposcomputo`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `controlequiposcomputo`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `controlequiposcomputo`.`tipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `controlequiposcomputo`;
INSERT INTO `controlequiposcomputo`.`tipo` (`id`, `nombre`, `estado`, `fecha_creacion`, `fecha_actualizacion`) VALUES (1, 'Computador', 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');
INSERT INTO `controlequiposcomputo`.`tipo` (`id`, `nombre`, `estado`, `fecha_creacion`, `fecha_actualizacion`) VALUES (2, 'Tablet', 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');
INSERT INTO `controlequiposcomputo`.`tipo` (`id`, `nombre`, `estado`, `fecha_creacion`, `fecha_actualizacion`) VALUES (3, 'Smartphone', 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');
INSERT INTO `controlequiposcomputo`.`tipo` (`id`, `nombre`, `estado`, `fecha_creacion`, `fecha_actualizacion`) VALUES (4, 'Servidor', 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');
INSERT INTO `controlequiposcomputo`.`tipo` (`id`, `nombre`, `estado`, `fecha_creacion`, `fecha_actualizacion`) VALUES (5, 'NAS', 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');

COMMIT;


-- -----------------------------------------------------
-- Data for table `controlequiposcomputo`.`estado`
-- -----------------------------------------------------
START TRANSACTION;
USE `controlequiposcomputo`;
INSERT INTO `controlequiposcomputo`.`estado` (`id`, `nombre`, `fecha_creacion`, `fecha_actualizacion`) VALUES (1, 'Habilitado', '2022-12-09 00:00:01', '2022-12-09 00:00:01');
INSERT INTO `controlequiposcomputo`.`estado` (`id`, `nombre`, `fecha_creacion`, `fecha_actualizacion`) VALUES (2, 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');
INSERT INTO `controlequiposcomputo`.`estado` (`id`, `nombre`, `fecha_creacion`, `fecha_actualizacion`) VALUES (3, 'Modificado', '2022-12-09 00:00:01', '2022-12-09 00:00:01');

COMMIT;


-- -----------------------------------------------------
-- Data for table `controlequiposcomputo`.`marca`
-- -----------------------------------------------------
START TRANSACTION;
USE `controlequiposcomputo`;
INSERT INTO `controlequiposcomputo`.`marca` (`id`, `nombre`, `estado`, `fecha_creacion`, `fecha_actualizacion`) VALUES (1, 'Dell', 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');
INSERT INTO `controlequiposcomputo`.`marca` (`id`, `nombre`, `estado`, `fecha_creacion`, `fecha_actualizacion`) VALUES (2, 'HP', 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');
INSERT INTO `controlequiposcomputo`.`marca` (`id`, `nombre`, `estado`, `fecha_creacion`, `fecha_actualizacion`) VALUES (3, 'Ryzer', 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');
INSERT INTO `controlequiposcomputo`.`marca` (`id`, `nombre`, `estado`, `fecha_creacion`, `fecha_actualizacion`) VALUES (4, 'MSi', 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');
INSERT INTO `controlequiposcomputo`.`marca` (`id`, `nombre`, `estado`, `fecha_creacion`, `fecha_actualizacion`) VALUES (5, 'Asus', 'Activo', '2022-12-09 00:00:01', '2022-12-09 00:00:01');

COMMIT;


-- -----------------------------------------------------
-- Data for table `controlequiposcomputo`.`rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `controlequiposcomputo`;
INSERT INTO `controlequiposcomputo`.`rol` (`id`, `nombre`) VALUES (1, 'Administrador');
INSERT INTO `controlequiposcomputo`.`rol` (`id`, `nombre`) VALUES (2, 'Docente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `controlequiposcomputo`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `controlequiposcomputo`;
INSERT INTO `controlequiposcomputo`.`usuario` (`id`, `nombre`, `email`, `password`, `estado`, `fecha_creacion`, `fecha_actualizacion`, `rol_id`) VALUES (1, 'Andrés', 'andres@gmail.com', '$2b$10$ZHbuZApE078AzKsuolugAujTAlWBNK5RmOgtw37YKLy3y2euH3LHa', 1, '2022-12-10 13:56:51', '2022-12-10 13:56:51', 1);
INSERT INTO `controlequiposcomputo`.`usuario` (`id`, `nombre`, `email`, `password`, `estado`, `fecha_creacion`, `fecha_actualizacion`, `rol_id`) VALUES (2, 'Daniela', 'daniela@gmail.com', '$2b$10$TGQsx23Snb1NJTm06U2wEOBeG/k.4GsNkJmvzksTDOw4lGzCkCm72', 1, '2022-12-10 13:58:45', '2022-12-10 13:58:45', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `controlequiposcomputo`.`inventario`
-- -----------------------------------------------------
START TRANSACTION;
USE `controlequiposcomputo`;
INSERT INTO `controlequiposcomputo`.`inventario` (`serial`, `modelo`, `descripcion`, `color`, `fecha_compra`, `precio`, `estado_id`, `tipo_id`, `marca_id`, `fecha_creacion`, `fecha_actualizacion`) VALUES ('SER1001', 2019, 'Equipo para desarrollo', 'Negro', '2022-05-05', 1000, 1, 1, 1, '2022-12-10 13:56:51', '2022-12-10 13:56:51');
INSERT INTO `controlequiposcomputo`.`inventario` (`serial`, `modelo`, `descripcion`, `color`, `fecha_compra`, `precio`, `estado_id`, `tipo_id`, `marca_id`, `fecha_creacion`, `fecha_actualizacion`) VALUES ('SER1002', 2020, 'Equipo para diseño', 'Negro', '2022-05-19', 1500, 1, 1, 1, '2022-12-10 13:56:51', '2022-12-10 13:56:51');

COMMIT;

